### ISSUE TITLE
More feedback

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/vulcanjs-cli#6]
Using version 1.2.2, I noticed the following issues:

- Routes use `component: Components.Foo` instead of `componentName: 'Foo'`
- Routes use `layoutName: 'Components.Foo'` instead of `layoutName: 'Foo'`
- Components still have indentation problems. 
- User group names are not pluralized (i.e. `member` instead of `members`).
- I think the `modules` directory should remain named `modules` instead of `models`, since it can contain things other than models. 

See also: https://www.twitch.tv/videos/161497431

**Comment by SachaG** [comment]
- Also I ran into this issue after trying to change the `origin` Git remote: https://stackoverflow.com/questions/28983842/remote-rejected-shallow-update-not-allowed-after-changing-git-remote-url

**Comment by albancrommer** [comment]
The shallow git situation occurs because we run `git clone`  wih `depth` argument, whi

**Comment by albancrommer** [comment]
sorry, closed by inadvertance

**Comment by albancrommer** [comment]
The shallow git situation occurs because we run `git clone`  using the `--depth 1` argument, which results in not retrieving the full project commits and objects. 
PRO: fast
CON: hard to understand, needs some action after some time

To fix it, run `git pull --unshallow`
as tested yesterday, the first depth option spares downloading 60K objects.

**Comment by mechanical-turk** [comment]
@albancrommer can you send a PR with the fix for git unshallow issue?

**Comment by albancrommer** [comment]
Of course I can, but I am not sure about how that would be best integrated. 

Maybe we should ask the user if the clone should be full (real install) or light (just testing) ?

I am not thrilled by the other option that would be to "fix" afterward by running git commands from the cli, but it's possible.

Last option, terminate the `--depth 1` argument. I do think it's better for speed, but I also understand the disadvantages.

**Comment by mechanical-turk** [comment]
@albancrommer i think the speed of the depth=1 solution is just too good to leave. Why are you against adding a git command to the install?

**Comment by SachaG** [comment]
- Another thing: the typename should be singular. So:

```
collectionName: 'Reviews',
  typeName: 'Review',
```

And not

```
collectionName: 'Reviews',
  typeName: 'Reviews',
```

**Comment by albancrommer** [comment]
@SachaG For now, I'm leaving the other bugs to @mechanical-turk who's responsible for that part of the code. 

@mechanical-turk '_adding a git command to the install_' would work for me, it all depends on how you do it. What would be the scenario? 

- questions, including "do you want a minimal clone for testing (fast/default) or a complete clone (slow)"
- clone according to answer ?

+ We offer an "unshallow" action that does the job afterward.

Would that work for you?

**Comment by mechanical-turk** [comment]
@albancrommer  i think we should clone with depth=1 automatically, without asking. and then immediately auto-run another command so that we can fix the shallow issue. can you think of any way to do that?

**Comment by mechanical-turk** [comment]
TODOS:

- [x] Routes use `component: Components.Foo` instead of `componentName: 'Foo'`
- [x] Routes use `layoutName: 'Components.Foo'` instead of `layoutName: 'Foo'`
- [ ] Components still have indentation problems. 
- [ ] User group names are not pluralized (i.e. `member` instead of `members`).
- [x] I think the `modules` directory should remain named `modules` instead of `models`, since it can contain things other than models.
